In [1]:
import pandas as pd

In [2]:
data={
    "Tid":[1,2,3,4,5,6,7,8,9,10],"Refund":["Yes","No","No","Yes","No","No","Yes","No","No","No"],
    "Marital_Status": [
        "Single", "Married", "Single", "Married", "Divorced",
        "Married", "Divorced", "Single", "Married", "Single"
    ],
    "Taxable_Income": [125, 100, 70, 120, 95, 60, 220, 85, 75, 90],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}
df= pd.DataFrame(data)
print(df)

   Tid Refund Marital_Status  Taxable_Income Cheat
0    1    Yes         Single             125    No
1    2     No        Married             100    No
2    3     No         Single              70    No
3    4    Yes        Married             120    No
4    5     No       Divorced              95   Yes
5    6     No        Married              60    No
6    7    Yes       Divorced             220    No
7    8     No         Single              85   Yes
8    9     No        Married              75    No
9   10     No         Single              90   Yes

In [3]:
print(df.iloc[[0, 4, 7, 8]])
print(df.iloc[3:8])
print(df.iloc[4:9,2:5])
print(df.iloc[:,1:4])

   Tid Refund Marital_Status  Taxable_Income Cheat
0    1    Yes         Single             125    No
4    5     No       Divorced              95   Yes
7    8     No         Single              85   Yes
8    9     No        Married              75    No
   Tid Refund Marital_Status  Taxable_Income Cheat
3    4    Yes        Married             120    No
4    5     No       Divorced              95   Yes
5    6     No        Married              60    No
6    7    Yes       Divorced             220    No
7    8     No         Single              85   Yes
  Marital_Status  Taxable_Income Cheat
4       Divorced              95   Yes
5        Married              60    No
6       Divorced             220    No
7         Single              85   Yes
8        Married              75    No
  Refund Marital_Status  Taxable_Income
0    Yes         Single             125
1     No        Married             100
2     No         Single              70
3    Yes        Married             120
4     No       Divorced              95
5     No        Married              60
6    Yes       Divorced             220
7     No         Single              85
8     No        Married              75
9     No         Single              90

In [4]:
csv_path="/content/Iris.csv"
ff=pd.read_csv(csv_path)
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: '/content/Iris.csv'

In [5]:
df.drop(index=4,inplace=True)
df

   Tid Refund Marital_Status  Taxable_Income Cheat
0    1    Yes         Single             125    No
1    2     No        Married             100    No
2    3     No         Single              70    No
3    4    Yes        Married             120    No
5    6     No        Married              60    No
6    7    Yes       Divorced             220    No
7    8     No         Single              85   Yes
8    9     No        Married              75    No
9   10     No         Single              90   Yes

In [6]:
df.drop(df.columns[3],axis=1,inplace=True)
df

   Tid Refund Marital_Status Cheat
0    1    Yes         Single    No
1    2     No        Married    No
2    3     No         Single    No
3    4    Yes        Married    No
5    6     No        Married    No
6    7    Yes       Divorced    No
7    8     No         Single   Yes
8    9     No        Married    No
9   10     No         Single   Yes

In [7]:

data = {
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Edward'],
    'Department': ['HR', 'IT', 'IT', 'Marketing', 'Sales'],
    'Age': [29, 34, 41, 28, 38],
    'Salary': [50000, 70000, 65000, 55000, 60000],
    'Years_of_Experience': [4, 8, 10, 3, 12],
    'Joining_Date': ['2020-03-15', '2017-07-19', '2013-06-01',
                     '2021-02-10', '2010-11-25'],
    'Gender': ['Female', 'Male', 'Male', 'Female', 'Male'],
    'Bonus': [5000, 7000, 6000, 4500, 5000],
    'Rating': [4.5, 4.0, 3.8, 4.7, 3.5]
}

df = pd.DataFrame(data)

df.to_csv('employees.csv', index=False)

print("employees.csv created successfully.")
print(df)

employees.csv created successfully.
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [8]:
print("Shape:", df.shape)

Shape: (5, 10)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [10]:
print(df.describe())

       Employee_ID        Age       Salary  Years_of_Experience   Bonus  \
count     5.000000   5.000000      5.00000             5.000000     5.0
mean    103.000000  34.000000  60000.00000             7.400000  5500.0
std       1.581139   5.612486   7905.69415             3.847077  1000.0
min     101.000000  28.000000  50000.00000             3.000000  4500.0
25%     102.000000  29.000000  55000.00000             4.000000  5000.0
50%     103.000000  34.000000  60000.00000             8.000000  5000.0
75%     104.000000  38.000000  65000.00000            10.000000  6000.0
max     105.000000  41.000000  70000.00000            12.000000  7000.0

         Rating
count  5.000000
mean   4.100000
std    0.494975
min    3.500000
25%    3.800000
50%    4.000000
75%    4.500000
max    4.700000

In [12]:
print(df.head(5))

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [11]:
print(df.tail(3))

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [13]:
average_salary = df['Salary'].mean()
print("Average Salary:", average_salary)

Average Salary: 60000.0

In [14]:
total_bonus = df['Bonus'].sum()
print("Total Bonus:", total_bonus)

Total Bonus: 27500

In [15]:
youngest_age = df['Age'].min()
print("Youngest Age:", youngest_age)

Youngest Age: 28

In [16]:
highest_rating = df['Rating'].max()
print("Highest Rating:", highest_rating)

Highest Rating: 4.7

In [17]:
sorted_df = df.sort_values(by='Salary', ascending=False)

print(sorted_df)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5

In [ ]:
def performance_category(rating):
    if rating >= 4.5:
        return 'Excellent'
    elif rating >= 4.0:
        return 'Good'
    else:
        return 'Average'

df['Performance'] = df['Rating'].apply(performance_category)

print(df)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating Performance
0   2020-03-15  Female   5000     4.5   Excellent
1   2017-07-19    Male   7000     4.0        Good
2   2013-06-01    Male   6000     3.8     Average
3   2021-02-10  Female   4500     4.7   Excellent
4   2010-11-25    Male   5000     3.5     Average

In [ ]:
print(df.isnull().sum())

Employee_ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
Performance            0
dtype: int64

In [ ]:
df.rename(columns={'Employee_ID': 'ID'}, inplace=True)

print(df)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating Performance
0  Female   5000     4.5   Excellent
1    Male   7000     4.0        Good
2    Male   6000     3.8     Average
3  Female   4500     4.7   Excellent
4    Male   5000     3.5     Average

In [ ]:
experience = df[df['Years_of_Experience'] > 5]

print(experience)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25

  Gender  Bonus  Rating Performance
1   Male   7000     4.0        Good
2   Male   6000     3.8     Average
4   Male   5000     3.5     Average

In [ ]:
it_employees = df[df['Department'] == 'IT']

print(it_employees)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating Performance
1   Male   7000     4.0        Good
2   Male   6000     3.8     Average

In [ ]:
df['Tax'] = df['Salary'] * 0.10

print(df)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating Performance     Tax
0  Female   5000     4.5   Excellent  5000.0
1    Male   7000     4.0        Good  7000.0
2    Male   6000     3.8     Average  6500.0
3  Female   4500     4.7   Excellent  5500.0
4    Male   5000     3.5     Average  6000.0

In [ ]:
df.to_csv('employees_modified.csv', index=False)

print("Modified dataset saved successfully.")

Modified dataset saved successfully.